name: Lint GitHub Actions workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    uses: nozomiishii/workflows/.github/workflows/actionlint.yaml@ec605e0a4f2acdb21166f3b430dd9345dd4dca2b # v1.1.0
